CREATE TABLE PERSONNE (
    CIN_PERSONNE Varchar(20) Key primary NOT NULL, 
    NOM_PERSONNE VARCHAR (80) NOT NULL,
    PRENOM_PERSONNE VARCHAR (80) NOT NULL,
    ADRESSE_PERSONNE Text NOT NULL, 
    VILLE_PERSONNE Varchar (200) NOT NULL,
    PASSWORD_PERSONNE Varchar (40) NOT NULL,
    GMAIL_PERSONNE Varchar (100) NOT NULL,
    STATUT_PERSONNE Varchar (100) NOT NULL,
    PHOTO_PERSONNE Varchar (200) NOT NULL,
    SALAIRE_PERSONNE  Float NOT NULL, 
    TRAVAIL_PERSONNE Varchar (200) NOT NULL, 
    LIEU_NAISSANCE Varchar (200) NOT NULL,
    COMPTE_FINANCIER Float NOT NULL,
    DATE_NAISSANCE Date NOT NULL,
    TEL_PERSONNE Varchar (15) NOT NULL
);
INSERT INTO personne(CIN_PERSONNE,NOM_PERSONNE,PRENOM_PERSONNE,ADRESSE_PERSONNE,VILLE_PERSONNE,PASSWORD_PERSONNE,GMAIL_PERSONNE,STATUT_PERSONNE,PHOTO_PERSONNE,SALAIRE_PERSONNE,TRAVAIL_PERSONNE,LIEU_NAISSANCE,COMPTE_FINANCIER,DATE_NAISSANCE)
VALUES('RX4517','EL MANSORI','SAID','HAY SALAM MOHAMMEDIA ','MOHAMMEDIA','0001','saidelmansori@gmail.com','celibataire','IMAGES/p3.jpg','12000',,'Etudiant','MOHAMMEDIA','240200','2000/02/24');


UPDATE personne SET NOM_PERSONNE='EL HADDIOUI',PRENOM_PERSONNE='MOHAMED',PHOTO_PERSONNE='IMAGE/p1.jpg',TRAVAIL_PERSONNE='Professeur',SALAIRE_PERSONNE='10000',VILLE_PERSONNE='AL HOCEIMA',GMAIL_PERSONNE='mohamedelhaddioui99@gmail.com',
STATUT_PERSONNE='celibataire',LIEU_NAISSANCE='IMZOUREN',DATE_NAISSANCE='1999/12/13',TEL_PERSONNE='0624389378',COMPTE_PERSONNE='249000',
ADRESSE_PERSONNE='$ADRESSE',PASSWORD_PERSONNE='$PASSWORD' WHERE CIN_PERSONNE='RX4517';